exclude: "^alembic/|^logs/"
default_stages: [pre-commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        files: ^app/
      - id: end-of-file-fixer
        files: ^app/
      - id: check-merge-conflict
        files: ^app/
      - id: debug-statements
        files: ^app/

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: ^app/

  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        files: ^app/
        exclude: '^.*\b(alembic)\b.*$|.*charity_project.*\.py$'

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.0
    hooks:
      - id: autoflake
        files: ^app/

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-use-type-annotations
        files: ^app/
      - id: python-check-blanket-noqa
        files: ^app/
